
# class person(object):
    
#     def __init__(self, name):
#         self.name = name
        
#     def getname(self):
#         return self.name
    
#     def isemployee(self):
#         return False
    
# class employee(person): # HERE WE SEE THAT EMPLOYEE IS A CLASS INHERITING FROM PERSON
    
#     def isemployee(self):
#         return True
    
# em = person("rahul")
# print(em.getname(), em.isemployee())
# em2 = person("anurag")
# print(em2.getname(), em2.isemployee())